#library(checkpoint)
#checkpoint("2019-05-15")

library(broom)
library(datasets)
library(DBI)
library(dplyr)
library(DT)
library(factoextra)
library(flextable)
library(fpc)
library(fs)
library(gdtools)
library(ggplot2) 
library(magrittr) # need to run every time you start R and want to use %>%
library(nFactors)
library(nortest)
library(officer)
library(plotrix)
library(plotly)
library(psych)
library(RColorBrewer)
library(rJava)
library(RWeka)
library(shiny)
library(shinyBS)
library(shinycssloaders)
library(shinydashboard)
library(shinyFiles)
library(SnowballC)
library(stats)
library(stringi)
library(tm)
library(wordcloud)

